//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SohelAfzalShajol_Playon24.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_Order
    {
        public int Pro_Order_ID { get; set; }
        public int Product_ID { get; set; }
        public int Customer_ID { get; set; }
        public int Quantity { get; set; }
        public double Total_Cost { get; set; }
        public System.DateTime Order_Date { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Customer_Register Customer_Register { get; set; }
        public virtual Product Product { get; set; }
    }
}
