//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SohelAfzalShajol_Playon24.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Pro_Order = new HashSet<Pro_Order>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Pro_Description { get; set; }
        public string Pro_Category { get; set; }
        public double Pro_Price { get; set; }
        public int Pro_Stock { get; set; }
        public string Pro_img { get; set; }
        public int EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsActive { get; set; }
        public string Pro_img_name { get; set; }
    
        public virtual Customer_Register Customer_Register { get; set; }
        public virtual Customer_Register Customer_Register1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_Order> Pro_Order { get; set; }
    }
}
